apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zvsq2ulvw-python 
  janus-idp.io/tekton: zvsq2ulvw-python
  backstage.io/kubernetes-id: zvsq2ulvw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zvsq2ulvw-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml