apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zvsq2ulvw-python
  janus-idp.io/tekton: zvsq2ulvw-python
  backstage.io/kubernetes-id: zvsq2ulvw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zvsq2ulvw-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
