apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zvsq2ulvw-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zvsq2ulvw-python 
  name: zvsq2ulvw-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zvsq2ulvw-python 
